"""added mdr tables

Revision ID: 44c6f85fd38f
Revises: 954a425b1a16
Create Date: 2026-02-25 13:07:01.559331

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '44c6f85fd38f'
down_revision = '954a425b1a16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('indic_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branch_indic_name'), 'branch', ['indic_name'], unique=True)
    op.create_index(op.f('ix_branch_name'), 'branch', ['name'], unique=True)
    op.create_index(op.f('ix_branch_short_name'), 'branch', ['short_name'], unique=True)
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    op.create_index(op.f('ix_category_short_name'), 'category', ['short_name'], unique=True)
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_name'), 'language', ['name'], unique=True)
    op.create_index(op.f('ix_language_short_name'), 'language', ['short_name'], unique=True)
    op.create_table('script',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_script_name'), 'script', ['name'], unique=True)
    op.create_index(op.f('ix_script_short_name'), 'script', ['short_name'], unique=True)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    op.create_index(op.f('ix_tag_short_name'), 'tag', ['short_name'], unique=True)
    op.create_table('type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_name'), 'type', ['name'], unique=True)
    op.create_index(op.f('ix_type_short_name'), 'type', ['short_name'], unique=True)
    op.create_table('discipline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('indic_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discipline_indic_name'), 'discipline', ['indic_name'], unique=True)
    op.create_index(op.f('ix_discipline_name'), 'discipline', ['name'], unique=True)
    op.create_index(op.f('ix_discipline_short_name'), 'discipline', ['short_name'], unique=True)
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('indic_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['discipline_id'], ['discipline.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_indic_name'), 'subject', ['indic_name'], unique=True)
    op.create_index(op.f('ix_subject_name'), 'subject', ['name'], unique=True)
    op.create_index(op.f('ix_subject_short_name'), 'subject', ['short_name'], unique=True)
    op.create_table('manuscript',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('accession_number', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('indic_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('diacritical_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('script_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('toc', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=True),
    sa.Column('subject_contribution', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('work_uniqueness', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('author_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('author_indic_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('author_diacritical_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('date_of_composition', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('pg_in_source', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('manuscript_code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('no_of_folios', sa.Integer(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('published_title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('translator_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('publisher_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('editor_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('publication_year', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('publication_place', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('no_of_pages', sa.Integer(), nullable=True),
    sa.Column('archive_link', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('beginning_line', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('ending_line', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('colophon', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['script.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manuscript_accession_number'), 'manuscript', ['accession_number'], unique=True)
    op.create_index(op.f('ix_manuscript_diacritical_name'), 'manuscript', ['diacritical_name'], unique=True)
    op.create_index(op.f('ix_manuscript_indic_name'), 'manuscript', ['indic_name'], unique=True)
    op.create_index(op.f('ix_manuscript_name'), 'manuscript', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manuscript_name'), table_name='manuscript')
    op.drop_index(op.f('ix_manuscript_indic_name'), table_name='manuscript')
    op.drop_index(op.f('ix_manuscript_diacritical_name'), table_name='manuscript')
    op.drop_index(op.f('ix_manuscript_accession_number'), table_name='manuscript')
    op.drop_table('manuscript')
    op.drop_index(op.f('ix_subject_short_name'), table_name='subject')
    op.drop_index(op.f('ix_subject_name'), table_name='subject')
    op.drop_index(op.f('ix_subject_indic_name'), table_name='subject')
    op.drop_table('subject')
    op.drop_index(op.f('ix_discipline_short_name'), table_name='discipline')
    op.drop_index(op.f('ix_discipline_name'), table_name='discipline')
    op.drop_index(op.f('ix_discipline_indic_name'), table_name='discipline')
    op.drop_table('discipline')
    op.drop_index(op.f('ix_type_short_name'), table_name='type')
    op.drop_index(op.f('ix_type_name'), table_name='type')
    op.drop_table('type')
    op.drop_index(op.f('ix_tag_short_name'), table_name='tag')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_script_short_name'), table_name='script')
    op.drop_index(op.f('ix_script_name'), table_name='script')
    op.drop_table('script')
    op.drop_index(op.f('ix_language_short_name'), table_name='language')
    op.drop_index(op.f('ix_language_name'), table_name='language')
    op.drop_table('language')
    op.drop_index(op.f('ix_category_short_name'), table_name='category')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_branch_short_name'), table_name='branch')
    op.drop_index(op.f('ix_branch_name'), table_name='branch')
    op.drop_index(op.f('ix_branch_indic_name'), table_name='branch')
    op.drop_table('branch')
    # ### end Alembic commands ###
