"""fk to discipline

Revision ID: 47e1e84d0835
Revises: 44c6f85fd38f
Create Date: 2026-02-25 13:17:19.447038

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '47e1e84d0835'
down_revision = '44c6f85fd38f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
