"""changes in manuscript & book tables

Revision ID: 76315730bf95
Revises: 3c3c566106ff
Create Date: 2026-03-06 22:14:05.070686

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "76315730bf95"
down_revision: Union[str, Sequence[str], None] = "3c3c566106ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("book", "date_of_composition")
    op.drop_column("book", "source")
    op.drop_column("book", "pg_in_source")
    op.add_column(
        "manuscript",
        sa.Column(
            "date_of_composition",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
    )
    op.add_column(
        "manuscript",
        sa.Column(
            "source", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
    )
    op.add_column(
        "manuscript",
        sa.Column(
            "pg_in_source", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
    )
    op.alter_column(
        "manuscript",
        "no_of_folios",
        existing_type=sa.Integer(),
        type_=sa.String(length=255),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("manuscript", "pg_in_source")
    op.drop_column("manuscript", "source")
    op.drop_column("manuscript", "date_of_composition")
    op.add_column(
        "book", sa.Column("pg_in_source", mysql.VARCHAR(length=255), nullable=True)
    )
    op.add_column("book", sa.Column("source", mysql.VARCHAR(length=255), nullable=True))
    op.add_column(
        "book",
        sa.Column("date_of_composition", mysql.VARCHAR(length=255), nullable=True),
    )
    op.alter_column(
        "manuscript",
        "no_of_folios",
        existing_type=sa.String(length=255),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
